#!/usr/local/autopkg/python
"""
ScriptInjector - AutoPkg Processor

Injects environment variables into shell scripts by prepending export statements.
Used for customizing bootstrap package scripts with team-specific variables.

Copyright 2024 Schrödinger, Inc.
"""

import os
from autopkglib import Processor, ProcessorError

__all__ = ["ScriptInjector"]


class ScriptInjector(Processor):
    """Inject environment variables into shell scripts"""

    description = __doc__
    input_variables = {
        "source_script": {
            "required": True,
            "description": "Path to source script file",
        },
        "destination_script": {
            "required": True,
            "description": "Path to output script file with injected variables",
        },
        "variables": {
            "required": True,
            "description": "Dictionary of environment variables to inject (key: value pairs)",
        },
    }
    output_variables = {}

    def main(self):
        source_script = self.env["source_script"]
        destination_script = self.env["destination_script"]
        variables = self.env["variables"]

        # Validate source exists
        if not os.path.exists(source_script):
            raise ProcessorError(f"Source script not found: {source_script}")

        # Read source script
        try:
            with open(source_script, "r") as f:
                source_content = f.read()
        except IOError as e:
            raise ProcessorError(f"Failed to read source script: {e}")

        # Remove shebang from source if present
        lines = source_content.splitlines()
        if lines and lines[0].startswith("#!"):
            source_content = "\n".join(lines[1:])

        # Build header with shebang and exports
        header_lines = ["#!/bin/bash", "# Generated by AutoPkg ScriptInjector"]

        # Add export statements for each variable
        for key, value in variables.items():
            # Escape double quotes in value
            escaped_value = value.replace('"', '\\"')
            header_lines.append(f'export {key}="{escaped_value}"')

        header_lines.append("")  # Blank line before original content

        # Combine header and source
        injected_content = "\n".join(header_lines) + "\n" + source_content

        # Write to destination
        try:
            # Create parent directory if needed
            dest_dir = os.path.dirname(destination_script)
            if dest_dir and not os.path.exists(dest_dir):
                os.makedirs(dest_dir)

            with open(destination_script, "w") as f:
                f.write(injected_content)

            # Make executable (0755)
            os.chmod(destination_script, 0o755)

        except IOError as e:
            raise ProcessorError(f"Failed to write destination script: {e}")

        self.output(f"Injected {len(variables)} variable(s) into {destination_script}")
        for key, value in variables.items():
            self.output(f"  {key}={value}")


if __name__ == "__main__":
    PROCESSOR = ScriptInjector()
    PROCESSOR.execute_shell()
